# Transient db - will lose it's data once restarted
version: "3"
services:
  mongo:
    container_name: mongo
    image: mongo:4.0
    restart: always
    command: mongod --replSet single_node_replica_set
    environment:
      MONGO_INITDB_ROOT_USERNAME: prisma
      MONGO_INITDB_ROOT_PASSWORD: prisma
    ports:
      - "127.0.0.1:27017:27017"
