version: "3"
services:
  app:
    image: prismagraphql/build-image:debian
    environment:
      SERVER_ROOT: /root/build
      CLUSTER_VERSION: "latest"
      COMMIT_SHA: "123abcd"
      PACKAGECLOUD_PW: "${PACKAGECLOUD_PW}"
      RABBITMQ_URI: amqp://rabbit
      PRISMA_CONFIG: |
        port: 4466
        prototype: true
        rabbitUri: amqp://rabbit
        databases:
          default:
            connector: sqlite
            migrations: true
            host: test-db
            port: 3306
            user: root
            password: prisma
            rawAccess: true
    volumes:
      - ../..:/root/build
      - ~/.ivy2:/root/.ivy2
      - ~/.coursier:/root/.coursier
    working_dir: /root/build
    networks:
      - tests

  rabbit:
    image: rabbitmq:3.7.2-management
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - tests

networks:
  tests:
